#!/bin/sh

cachedir="${XDG_CACHE_HOME:-"$HOME/.cache"}"
cache="$cachedir/dmenu_run"

[ ! -e "$cachedir" ] && mkdir -p "$cachedir"

IFS=:
if stest -dqr -n "$cache" "$PATH"; then
	stest -flx "$PATH" | sort -u > "$cache"
fi
if [ "${SHELL%/zsh}"  != "$SHELL" ]; then
    "$SHELL" -ic alias | grep -Eo "^[^=]+"
fi
cat "$cache"
